### ISSUE TITLE
Missing requires

### ISSUE THREAD

**Issue by berbagimadani** [scriptituk/xfade-easing#1]
I have followed this but it doesn't work
this script requires Bash 4 (2009), gawk, gsed, envsubst, ffmpeg, gnuplot, base64
gsed or sed ?

xfade-easing.sh -t wipedown -e cubic -x - 
xfade-easing.sh -f option

Error: missing dependencies: gawk gsed envsubst gnuplot ffmpeg seq base64
os: ubuntu 22.04

anyone can help ? Thank you

**Comment by scriptituk** [comment]
Thank you for your feedback.

Version 2.0.0 requires just ffmpeg, gawk, gsed & seq.

- Bash 4 is 15 years old and has many features that make shell scripting much easier; even Bash 5 is 6 years old!
- gnuplot is only required now for plotting easing graphs.
- seq is standard in most distros.
- base64 in quite standard too but only required if no input files are given on the CLI.
- gawk & gsed are much improved versions of awk & sed, again quite standard but they might be aliased as awk & sed.
- envsubst is used for the -H help option but there's a workaround now if it's not installed.

Sorry for the tight prerequisites but they are looser now with version 2.

**Comment by scriptituk** [comment]
base64 is no longer required in v2.1.0.
