### ISSUE TITLE
Convert glsl

### ISSUE THREAD

**Issue by abdurrahimgayretli** [scriptituk/xfade-easing#2]
how to convert glsl to custom expression like you?

**Comment by scriptituk** [comment]
Haha! Answer:

1. years of Assembler coding
2. years of Reverse Polish coding
3. years of learning to play music by J.S.Bach
4. boredom with Sudoku!

Converting GLSL to C in [xfade-easing.h](../tree/main/src/xfade-easing.h) was more fun.

I wonder if the custom expressions will be considered useful or a big joke!

**Comment by abdurrahimgayretli** [comment]
I'm trying to make video transitions with gl-transition using ffmpeg wasm with react in the browser. Thanks to you, I was able to meet most of the gl-transition code that you converted into custom expressions. So I asked you how to convert all gl-transition into custom expressions. Could you translate it for me?

**Comment by scriptituk** [comment]
Ok, I misunderstood your first question.
I don't really understand your second question.

Are you asking if I used a tool or app to convert GLSL to ffmpeg custom expressions?
No, I analysed the transition GLSL then converted it manually to custom expressions in [xfade-easing.sh](../tree/main/src/xfade-easing.sh) and to C code in [xfade-easing.h](../tree/main/src/xfade-easing.h).

For complex transitions like `InvertedPageCurl` I first simplified the GLSL using the [editor](https://gl-transitions.com/editor) to remove function calls and separate vector components.

Are you raising an issue or asking advice?
I have no WebAssembly experience but if you can build a custom ffmpeg.wasm [compare here for C](../tree/main/README.md#custom-ffmpeg-variant) then all the gl transitions in [xfade-easing.h](../tree/main/src/xfade-easing.h) will run.

Sorry I cannot help.
