### ISSUE TITLE
Does this plugin support the version of ffmpeg?

### ISSUE THREAD

**Issue by iMactool** [scriptituk/xfade-easing#3]
Does this plugin support the version of ffmpeg?

**Comment by scriptituk** [comment]
I do not understand the question. Is it an issue?

The native ffmpeg build patches libavfilter version 9 but earlier versions can easily be merged.

The script runs on ffmpeg versions that have xfade.

**Comment by iMactool** [comment]
sorry.  ffmpeg version 6.1.1   is support ?
----
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-avfilter --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --enable-runtime-cpudetect --enable-frei0r --enable-libharfbuzz --enable-libfontconfig --enable-libfribidi
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Hyper fast Audio and Video encoder

on make...

![企业微信截图_17132667664395](https://github.com/scriptituk/xfade-easing/assets/3078413/8bf80410-74ed-46d9-b6b5-f2aa059f5ae1)

**Comment by iMactool** [comment]
@scriptituk  Thank you very much. I hope you can reply when you have time.

```
skipping strip -x libavfilter/x86/colorspacedsp.o
CC	libswscale/alphablend.o
cc1: some warnings being treated as errors
CC	libswscale/gamma.o
CC	libswscale/half2float.o
STRIP	libavfilter/x86/vf_lut3d.o
skipping strip -x libavfilter/x86/vf_lut3d.o
CC	libswscale/hscale.o
make: *** [ffbuild/common.mak:81: libavfilter/vf_xfade.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by iMactool** [comment]
https://github.com/scriptituk/xfade-easing/blob/main/src/xfade-easing.h
change:
```
static void xe_debug(void *avcl, const char *fmt, ...) // emits parsing trail
{
    const char *p = "xfade-easing: ";
    int l = strlen(p) + strlen(fmt) + 1;
    char f[1000];  # change here ( char f[l];) can make.
    av_strlcpy(f, p, l);
    av_strlcat(f, fmt, l);
    va_list args;
    va_start(args, fmt);
    av_vlog(avcl, AV_LOG_DEBUG, f, args);
    va_end(args);
}
```
Given an inaccurate constant like this, it is currently possible to compile it successfully

**Comment by scriptituk** [comment]
I have removed this variable length array.
VLA support in C99, C11, C23 is confusing!
Thank you for alerting this problem.
